baseURL = "https://adhdevops.club/"
languageCode = "en-us"
title = "ADHDevOps.club"
theme = "ezhil"
paginate = 5
copyright = "ADHDevOps.club © 2021"

[permalinks]
posts = "/posts/:year/:month/:day/:slug/"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = ""

summaryLength = 20

[params]
disableDisqusTypes = ["page"]
featherIconsCDN = true

# Light or dark theme. "auto" is based on user's browser preferences
themeColor = "light" # "dark", "auto", "light"

# lives in static/ directory of site
logo = "simple-logo-light-mode.png"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/adhdevops/adhdevops.club"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
