languageCode: "en-us"
baseUrl: "https://adhdevops.club"
title: "ADHDevOps.club"
theme: "anubis"
paginate: 10

permalinks:
  posts: /posts/:year/:month/:day/:slug/

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "ADHDevOps.club"
  # email: mail@example.org # used for microformats
  # avatar: "/images/me.png" # used for microformats

  # used by twitter cards, etc.
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: true
  disableSummary: false

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
